---
script: bundle exec rake

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - jruby

notifications:
  email:
    recipients:
      - development@olery.com
    email:
      on_success: change
      on_failure: change

branches:
  only:
    - master

#cache: bundler
