---
script: rake

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0-preview1
  - jruby
  - jruby-head
  - jruby-1.7.4
  - rbx-2.2.1

notifications:
  email:
    recipients:
      - development@olery.com
    email:
      on_success: change
      on_failure: change

branches:
  only:
    - master
