---
script: rake

rvm:
  - 1.9.3
  - 2.0.0
  - rbx-2.1.1
  - rbx-head
  - jruby-19mode
  - jruby-head

notifications:
  email:
    recipients:
      - development@olery.com
    email:
      on_success: change
      on_failure: always

branches:
  only:
    - master
